import { useState } from "react";
import { useSelector } from "react-redux";
import { Navigate } from "react-router-dom";
import { useAcceptDeliveryMutation, useApplyAsRiderMutation, useGetRiderDashboardQuery, useSubmitRestaurantLeadMutation, useUpdateRiderAvailabilityMutation, useUpdateRiderDeliveryMutation } from "../../app/api.js";

const applicationInitial = { vehicleType: "bicycle", vehicleNumber: "", drivingLicenseNumber: "", city: "", serviceAreas: "", upiId: "", emergencyContact: "" };
const leadInitial = { restaurantName: "", ownerName: "", ownerPhone: "", ownerEmail: "", city: "", address: "", cuisines: "", notes: "" };
const errorText = (error) => error?.data?.message ?? "Something went wrong. Please try again.";

function RiderApplication() {
  const [form, setForm] = useState(applicationInitial);
  const [apply, request] = useApplyAsRiderMutation();
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event) => { event.preventDefault(); try { await apply({ ...form, serviceAreas: form.serviceAreas.split(",").map((value) => value.trim()).filter(Boolean) }).unwrap(); } catch { /* shown */ } };
  return <main className="rider-apply"><section><span className="kicker light">Earn on your schedule</span><h1>Become a Plateful rider.</h1><p>Deliver nearby orders, introduce trusted local restaurants, and earn from both activities.</p><ul><li>Choose when you go online</li><li>Keep the delivery fee collected for assigned trips</li><li>Earn 20% of Plateful’s commission from restaurants you refer</li></ul></section><form onSubmit={submit}><span className="kicker">Rider application</span><h2>Tell us about yourself</h2><label>Vehicle<select name="vehicleType" value={form.vehicleType} onChange={update}><option value="bicycle">Bicycle</option><option value="motorcycle">Motorcycle</option><option value="scooter">Scooter</option><option value="car">Car</option></select></label><label>Vehicle number<input name="vehicleNumber" value={form.vehicleNumber} onChange={update} placeholder="Optional for bicycle"/></label><label>Driving licence<input name="drivingLicenseNumber" value={form.drivingLicenseNumber} onChange={update} placeholder="Required for motor vehicles"/></label><label>City<input name="city" value={form.city} onChange={update} required/></label><label>Service areas<input name="serviceAreas" value={form.serviceAreas} onChange={update} required placeholder="Indiranagar, Koramangala"/><small>Separate areas with commas</small></label><label>UPI ID for payouts<input name="upiId" value={form.upiId} onChange={update} required placeholder="name@bank"/></label><label>Emergency contact<input name="emergencyContact" value={form.emergencyContact} onChange={update} required/></label>{request.error && <div className="owner-error">{errorText(request.error)}</div>}<button disabled={request.isLoading}>{request.isLoading ? "Submitting…" : "Apply to ride"}</button></form></main>;
}

function LeadForm() {
  const [form, setForm] = useState(leadInitial);
  const [submitLead, request] = useSubmitRestaurantLeadMutation();
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event) => { event.preventDefault(); try { await submitLead({ ...form, cuisines: form.cuisines.split(",").map((value) => value.trim()).filter(Boolean) }).unwrap(); setForm(leadInitial); } catch { /* shown */ } };
  return <form className="rider-lead-form" onSubmit={submit}><h2>Add a local restaurant</h2><p>Only submit owners who agreed to be contacted by Plateful.</p><label>Restaurant<input name="restaurantName" value={form.restaurantName} onChange={update} required/></label><label>Owner name<input name="ownerName" value={form.ownerName} onChange={update} required/></label><label>Owner phone<input name="ownerPhone" value={form.ownerPhone} onChange={update} required/></label><label>Owner email<input type="email" name="ownerEmail" value={form.ownerEmail} onChange={update} required/></label><label>City<input name="city" value={form.city} onChange={update} required/></label><label>Full address<input name="address" value={form.address} onChange={update} required/></label><label className="full">Cuisines<input name="cuisines" value={form.cuisines} onChange={update} required placeholder="North Indian, Fast Food"/></label><label className="full">Notes<textarea name="notes" value={form.notes} onChange={update}/></label>{request.error && <div className="owner-error full">{errorText(request.error)}</div>}<button className="full" disabled={request.isLoading}>Submit restaurant lead</button></form>;
}

export function RiderPage() {
  const user = useSelector((state) => state.auth.user);
  const { data, isLoading } = useGetRiderDashboardQuery(undefined, { skip: !user, pollingInterval: 15000 });
  const [availability] = useUpdateRiderAvailabilityMutation();
  const [accept] = useAcceptDeliveryMutation();
  const [advance] = useUpdateRiderDeliveryMutation();
  if (!user) return <Navigate to="/login" replace/>;
  if (isLoading) return <main className="page-state tall">Loading rider workspace…</main>;
  const dashboard = data?.data;
  if (!dashboard?.profile) return <RiderApplication/>;
  const { profile, leads, earnings, availableOrders, activeOrder } = dashboard;
  if (profile.status !== "approved") return <main className="rider-status"><span className={`status-badge ${profile.status}`}>{profile.status}</span><h1>Rider application {profile.status}</h1><p>{profile.status === "pending" ? "Our operations team will review your details before you can accept deliveries." : profile.rejectionReason || "Contact support for more information."}</p></main>;
  return <main className="rider-dashboard"><section className="rider-dashboard-head"><div><span className="kicker">Rider partner</span><h1>Welcome, {user.name.split(" ")[0]}</h1><p>{profile.city} · {profile.vehicleType}</p></div><label className="rider-online"><input type="checkbox" checked={profile.isAvailable} onChange={(event) => availability({ isAvailable: event.target.checked })}/><span>{profile.isAvailable ? "Online" : "Offline"}</span></label></section><section className="rider-stats"><article><span>Total earnings</span><b>₹{profile.totalEarnings.toFixed(2)}</b></article><article><span>Deliveries</span><b>{profile.completedDeliveries}</b></article><article><span>Referral earnings</span><b>₹{profile.referralEarnings.toFixed(2)}</b></article><article><span>Restaurants added</span><b>{profile.referredRestaurants}</b></article></section>{activeOrder && <section className="rider-active"><span>ACTIVE DELIVERY</span><h2>{activeOrder.restaurantSnapshot.name}</h2><p>{activeOrder.orderNumber} · {activeOrder.deliveryAddress.line1}, {activeOrder.deliveryAddress.area}</p><b>Delivery earning ₹{activeOrder.financials.riderDeliveryEarning.toFixed(2)}</b>{activeOrder.status === "ready_for_pickup" && <button onClick={() => advance({ id: activeOrder._id, status: "out_for_delivery" })}>Picked up · start delivery</button>}{activeOrder.status === "out_for_delivery" && <button onClick={() => advance({ id: activeOrder._id, status: "delivered" })}>Mark delivered</button>}</section>}<div className="rider-grid"><section><h2>Available deliveries</h2>{!profile.isAvailable ? <p className="empty-state">Go online to see nearby pickup jobs.</p> : availableOrders.length === 0 ? <p className="empty-state">No pickup jobs available right now.</p> : availableOrders.map((order) => <article className="delivery-job" key={order._id}><div><b>{order.restaurantSnapshot.name}</b><span>{order.deliveryDistanceKm.toFixed(1)} km · {order.deliveryAddress.area}</span></div><strong>₹{order.financials.riderDeliveryEarning.toFixed(2)}</strong><button onClick={() => accept(order._id)}>Accept</button></article>)}</section><section><h2>Recent earnings</h2>{earnings.length === 0 ? <p className="empty-state">Completed delivery and referral earnings appear here.</p> : earnings.map((earning) => <article className="earning-row" key={earning._id}><div><b>{earning.type === "delivery" ? "Delivery" : "Restaurant referral"}</b><span>{earning.restaurant?.name}</span></div><strong>+₹{earning.amount.toFixed(2)}</strong></article>)}</section></div><LeadForm/><section className="rider-leads"><h2>Your restaurant leads</h2>{leads.map((lead) => <article key={lead._id}><div><b>{lead.restaurantName}</b><span>{lead.ownerName} · {lead.city}</span></div><span className={`status-badge ${lead.status}`}>{lead.status}</span></article>)}</section></main>;
}
