import { Router } from "express";
import { authenticate, authorize } from "../../middleware/authenticate.js";
import { validate } from "../../middleware/validate.js";
import { listAllOrders, listApplications, listAudit, listReviews, listRiders, listUsers, markRiderEarningPaid, moderateReview, operateRestaurant, reviewRestaurant, reviewRestaurantLead, reviewRider, updateUserStatus } from "./admin.controller.js";
import { earningPayoutSchema, leadDecisionSchema, riderDecisionSchema } from "../riders/rider.schemas.js";
import { restaurantOperationSchema, reviewModerationSchema, reviewRestaurantSchema, userStatusSchema } from "./admin.schemas.js";

export const adminRouter = Router();
adminRouter.use(authenticate, authorize("admin"));
adminRouter.get("/restaurants", listApplications);
adminRouter.patch("/restaurants/:restaurantId/status", validate(reviewRestaurantSchema), reviewRestaurant);
adminRouter.patch("/restaurants/:restaurantId/operation", validate(restaurantOperationSchema), operateRestaurant);
adminRouter.get("/users", listUsers);
adminRouter.patch("/users/:userId/status", validate(userStatusSchema), updateUserStatus);
adminRouter.get("/orders", listAllOrders);
adminRouter.get("/reviews", listReviews);
adminRouter.patch("/reviews/:reviewId", validate(reviewModerationSchema), moderateReview);
adminRouter.get("/audit", listAudit);
adminRouter.get("/riders", listRiders);
adminRouter.patch("/riders/:riderId", validate(riderDecisionSchema), reviewRider);
adminRouter.patch("/restaurant-leads/:leadId", validate(leadDecisionSchema), reviewRestaurantLead);
adminRouter.patch("/rider-earnings/:earningId", validate(earningPayoutSchema), markRiderEarningPaid);
